apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-app
  labels:
    app: gitops-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-demo-app
  template:
    metadata:
      labels:
        app: gitops-demo-app
    spec:
      containers:
      - name: gitops-demo-app
        image: ghcr.io/johanbriys/gitops-demo-app:latest
        ports:
        - containerPort: 5000
